package catalog

const (
	audioExts = ".mp3,.wav,.flac,.m4a,.opus,.ogg,.aac,.wma"
	imageExts = ".png,.jpg,.jpeg,.webp,.bmp,.tiff"
	docExts   = ".pdf,.docx,.pptx,.xlsx,.epub,.html"
)

var tasks = []Task{
	{
		ID:          "stems",
		Title:       "Stem Separator",
		Group:       "Audio",
		Description: "Split a track into vocals, drums, bass and accompaniment, or straight into a karaoke pair.",
		Engine:      "Demucs (htdemucs)",
		Icon:        "audio-lines",
		Project:     "stems",
		Params: []Param{
			{Name: "input", Label: "Audio file", Type: ParamFile, Required: true, Accept: audioExts},
			{Name: "model", Label: "Model", Type: ParamSelect, Default: "htdemucs", Options: []Option{
				{Value: "htdemucs", Label: "htdemucs (fast, 4 stems)"},
				{Value: "htdemucs_ft", Label: "htdemucs_ft (fine-tuned, slower)"},
				{Value: "htdemucs_6s", Label: "htdemucs_6s (adds guitar and piano)"},
				{Value: "mdx_extra", Label: "mdx_extra"},
			}},
			{Name: "two-stems", Label: "Two-stem mode (vocals vs instrumental)", Type: ParamBool},
			{Name: "format", Label: "Output format", Type: ParamSelect, Default: "wav", Options: []Option{
				{Value: "wav", Label: "WAV"},
				{Value: "mp3", Label: "MP3 320k"},
			}},
			{Name: "shifts", Label: "Shift passes", Type: ParamNumber, Default: "1", Min: 0, Max: 5, Step: 1,
				Help: "Averaging passes that trade time for separation quality."},
		},
	},
	{
		ID:          "denoise",
		Title:       "Audio Enhancer",
		Group:       "Audio",
		Description: "Strip room noise, hum and static out of a voice recording.",
		Engine:      "DeepFilterNet3",
		Icon:        "waves",
		Project:     "denoise",
		Params: []Param{
			{Name: "input", Label: "Audio file", Type: ParamFile, Required: true, Accept: audioExts},
			{Name: "attenuation", Label: "Noise reduction strength", Type: ParamNumber, Default: "100",
				Min: 5, Max: 100, Step: 5, Help: "Caps how far noise is pushed down, in dB."},
			{Name: "keep-original", Label: "Keep the original alongside the result", Type: ParamBool, Default: "true"},
		},
	},
	{
		ID:          "transcribe",
		Title:       "Transcriber",
		Group:       "Audio",
		Description: "Turn speech into text, timestamps and subtitles.",
		Engine:      "MLX Whisper",
		Icon:        "captions",
		Project:     "transcribe",
		Params: []Param{
			{Name: "input", Label: "Audio or video file", Type: ParamFile, Required: true, Accept: audioExts + ",.mp4,.mov,.mkv,.webm"},
			{Name: "model", Label: "Model", Type: ParamSelect, Default: "mlx-community/whisper-large-v3-turbo", Options: []Option{
				{Value: "mlx-community/whisper-large-v3-turbo", Label: "large-v3-turbo (recommended)"},
				{Value: "mlx-community/whisper-large-v3-mlx", Label: "large-v3 (most accurate)"},
				{Value: "mlx-community/whisper-medium-mlx", Label: "medium"},
				{Value: "mlx-community/whisper-small-mlx", Label: "small (fastest)"},
			}},
			{Name: "task", Label: "Task", Type: ParamSelect, Default: "transcribe", Options: []Option{
				{Value: "transcribe", Label: "Transcribe"},
				{Value: "translate", Label: "Translate to English"},
			}},
			{Name: "language", Label: "Language", Type: ParamText, Help: "ISO code such as en or fr. Leave empty to detect."},
			{Name: "word-timestamps", Label: "Word-level timestamps", Type: ParamBool},
		},
	},
	{
		ID:          "dictate",
		Title:       "Dictation",
		Group:       "Speech",
		Description: "Speak into the browser and get clean written text back, spelled the way you want it.",
		Engine:      "Qwen3-ASR + Gemma 4",
		Icon:        "mic-vocal",
		Project:     "dictate",
		Params: []Param{
			{Name: "input", Label: "Recording", Type: ParamFile, Required: true, Widget: "record",
				Accept: audioExts + ",.webm,.mp4"},
			{Name: "lexicon", Label: "Vocabulary and corrections", Type: ParamFile, Widget: "lexicon", Accept: ".json",
				Help: "Spellings to hold on to, and phrases the recogniser has got wrong before. Saved for every device."},
			{Name: "asr-model", Label: "Recognizer", Type: ParamSelect, Default: "Qwen/Qwen3-ASR-1.7B", Options: []Option{
				{Value: "Qwen/Qwen3-ASR-1.7B", Label: "Qwen3-ASR 1.7B (recommended)"},
				{Value: "Qwen/Qwen3-ASR-0.6B", Label: "Qwen3-ASR 0.6B (faster, lighter)"},
			}},
			{Name: "polish", Label: "Polish the transcript into written text", Type: ParamBool, Default: "true"},
			{Name: "polish-model", Label: "Polish model", Type: ParamSelect, Default: "mlx-community/gemma-4-12B-it-4bit",
				VisibleWhen: &Condition{Param: "polish", Equals: "true"}, Options: []Option{
					{Value: "mlx-community/gemma-4-12B-it-4bit", Label: "Gemma 4 12B, 4-bit (recommended)"},
					{Value: "mlx-community/gemma-4-12B-it-8bit", Label: "Gemma 4 12B, 8-bit (slower, more memory)"},
				}},
			{Name: "language", Label: "Language", Type: ParamText,
				Help: "Language name such as English or French. Leave empty to detect."},
		},
	},
	{
		ID:          "tts",
		Title:       "Speech Synthesis",
		Group:       "Speech",
		Description: "Read text aloud in a natural preset voice, near instantly.",
		Engine:      "Kokoro 82M",
		Icon:        "mic",
		Project:     "tts",
		Params: []Param{
			{Name: "text", Label: "Text", Type: ParamTextarea, Required: true},
			{Name: "voice", Label: "Voice", Type: ParamSelect, Default: "af_heart", Options: []Option{
				{Value: "af_heart", Label: "Heart (American, female)"},
				{Value: "af_bella", Label: "Bella (American, female)"},
				{Value: "af_nicole", Label: "Nicole (American, female)"},
				{Value: "am_adam", Label: "Adam (American, male)"},
				{Value: "am_michael", Label: "Michael (American, male)"},
				{Value: "bf_emma", Label: "Emma (British, female)"},
				{Value: "bf_isabella", Label: "Isabella (British, female)"},
				{Value: "bm_george", Label: "George (British, male)"},
				{Value: "bm_lewis", Label: "Lewis (British, male)"},
			}},
			{Name: "speed", Label: "Speed", Type: ParamNumber, Default: "1.0", Min: 0.5, Max: 2.0, Step: 0.1},
			{Name: "format", Label: "Output format", Type: ParamSelect, Default: "wav", Options: []Option{
				{Value: "wav", Label: "WAV"},
				{Value: "mp3", Label: "MP3"},
			}},
		},
	},
	{
		ID:          "voiceclone",
		Title:       "Voice Cloning",
		Group:       "Speech",
		Description: "Speak new text in a voice taken from a short reference clip.",
		Engine:      "F5-TTS (MLX)",
		Icon:        "user-round-cog",
		Project:     "voiceclone",
		Params: []Param{
			{Name: "text", Label: "Text to speak", Type: ParamTextarea, Required: true},
			{Name: "preset", Label: "Reference voice", Type: ParamSelect, Default: "warm-narrator", Options: []Option{
				{Value: "warm-narrator", Label: "Warm Narrator"},
				{Value: "studio-host", Label: "Studio Host"},
				{Value: "casual-peercast", Label: "Casual Peercast"},
				{Value: "custom", Label: "My own voice"},
			}},
			{Name: "ref-audio", Label: "Reference clip (5-15s)", Type: ParamFile, Widget: "capture",
				Accept:      audioExts + ",.webm,.mp4",
				VisibleWhen: &Condition{Param: "preset", Equals: "custom"},
				Help:        "Anything past 15 seconds is cut, because F5-TTS garbles a longer reference."},
			{Name: "ref-text", Label: "Reference transcript", Type: ParamTextarea,
				VisibleWhen: &Condition{Param: "preset", Equals: "custom"},
				Help: "Exactly what is said in the clip. Leave empty to transcribe it automatically, " +
					"which also happens when a longer clip has to be cut."},
			{Name: "speed", Label: "Speed", Type: ParamNumber, Default: "1.0", Min: 0.5, Max: 2.0, Step: 0.1},
		},
	},
	{
		ID:          "chat",
		Title:       "Small Model Chat",
		Group:       "Chat",
		Description: "Talk to a local Gemma about text, pictures and recordings, for as long as you like.",
		Engine:      "Gemma 4 (MLX)",
		Icon:        "messages-square",
		Project:     "chat",
		Interactive: true,
		Params: []Param{
			{Name: "model", Label: "Model", Type: ParamSelect, Default: "mlx-community/gemma-4-e4b-it-4bit",
				Options: []Option{
					{Value: "mlx-community/gemma-4-e2b-it-4bit", Label: "Gemma 4 E2B, 4-bit (fastest, 4 GB download)"},
					{Value: "mlx-community/gemma-4-e4b-it-4bit", Label: "Gemma 4 E4B, 4-bit (recommended, 5 GB download)"},
					{Value: "mlx-community/gemma-4-12B-it-4bit", Label: "Gemma 4 12B, 4-bit (7 GB download)"},
					{Value: "mlx-community/gemma-4-12B-it-8bit", Label: "Gemma 4 12B, 8-bit (sharper, 13 GB download)"},
					{Value: "mlx-community/gemma-4-26b-a4b-it-4bit", Label: "Gemma 4 26B A4B, 4-bit (no voice, 15 GB download)"},
					{Value: "mlx-community/gemma-4-31b-it-4bit", Label: "Gemma 4 31B, 4-bit (no voice, 18 GB download)"},
				},
				Help: "Weights download once and load on the first message. The two largest carry no audio " +
					"encoder, so they read pictures but cannot listen to a recording."},
			{Name: "system", Label: "System prompt", Type: ParamTextarea,
				Help: "Standing instructions placed ahead of the conversation. Leave empty for none."},
		},
	},
	{
		ID:          "doc2md",
		Title:       "Document to Markdown",
		Group:       "Documents",
		Description: "Convert a PDF or office document into clean Markdown, keeping tables and equations.",
		Engine:      "Marker",
		Icon:        "file-text",
		Project:     "doc2md",
		Params: []Param{
			{Name: "input", Label: "Document", Type: ParamFile, Required: true, Accept: docExts},
			{Name: "pages", Label: "Page range", Type: ParamText, Help: "For example 1-10. Leave empty for the whole document."},
			{Name: "format", Label: "Output format", Type: ParamSelect, Default: "markdown", Options: []Option{
				{Value: "markdown", Label: "Markdown"},
				{Value: "html", Label: "HTML"},
				{Value: "json", Label: "JSON"},
			}},
			{Name: "force-ocr", Label: "Force OCR on every page", Type: ParamBool,
				Help: "Use when the embedded text layer is missing or wrong."},
		},
	},
	{
		ID:          "ocr",
		Title:       "Image OCR",
		Group:       "Documents",
		Description: "Read text, layout and tables out of a screenshot, receipt or photo.",
		Engine:      "Surya",
		Icon:        "scan-text",
		Project:     "ocr",
		Params: []Param{
			{Name: "input", Label: "Image", Type: ParamFile, Required: true, Accept: imageExts},
			{Name: "tables", Label: "Recognize tables", Type: ParamBool, Default: "true"},
			{Name: "annotate", Label: "Annotated preview", Type: ParamBool, Default: "true"},
		},
	},
	{
		ID:          "imagegen",
		Title:       "Image Generation",
		Group:       "Images",
		Description: "Draw an image from a written description, in a single pass.",
		Engine:      "Z-Image Turbo",
		Icon:        "wand-sparkles",
		Project:     "imagegen",
		Params: []Param{
			{Name: "prompt", Label: "Prompt", Type: ParamTextarea, Required: true,
				Help: "Describe the picture. Subject, setting, lighting and style all steer the result."},
			{Name: "model", Label: "Model", Type: ParamSelect, Default: "z-image-turbo-4bit", Options: []Option{
				{Value: "z-image-turbo-4bit", Label: "Z-Image Turbo 6B, 4-bit (recommended, 6 GB download)"},
				{Value: "z-image-turbo", Label: "Z-Image Turbo 6B, 8-bit (sharper, 33 GB download)"},
				{Value: "flux2-klein-4b", Label: "FLUX.2 Klein 4B, 8-bit (fewest steps, 24 GB download)"},
				{Value: "qwen-image", Label: "Qwen-Image 20B, 8-bit (long prompts, 58 GB download)"},
			}},
			{Name: "size", Label: "Size", Type: ParamSelect, Default: "1024x1024", Options: []Option{
				{Value: "1024x1024", Label: "Square 1024 x 1024"},
				{Value: "1280x720", Label: "Landscape 1280 x 720"},
				{Value: "720x1280", Label: "Portrait 720 x 1280"},
				{Value: "1536x864", Label: "Wide 1536 x 864"},
			}},
			{Name: "seed", Label: "Seed", Type: ParamText, Widget: "seed",
				Help: "The same seed and prompt reproduce the same picture. Empty draws a new one every run."},
			{Name: "steps", Label: "Steps", Type: ParamNumber, Default: "0", Min: 0, Max: 50, Step: 1,
				Help: "0 uses the step count the chosen model was distilled for."},
			{Name: "lora", Label: "LoRA", Type: ParamText,
				Help: "HuggingFace repo or .safetensors path, several separated by commas. " +
					"Add :0.5 to set its strength."},
		},
	},
	{
		ID:          "upscale",
		Title:       "Image Upscaler",
		Group:       "Images",
		Description: "Raise the resolution of an image without the softness of a plain resize.",
		Engine:      "Real-ESRGAN",
		Icon:        "image-up",
		Project:     "upscale",
		Params: []Param{
			{Name: "input", Label: "Image", Type: ParamFile, Required: true, Accept: imageExts},
			{Name: "model", Label: "Model", Type: ParamSelect, Default: "anime6b", Options: []Option{
				{Value: "anime6b", Label: "Anime 6B (illustration, line art)"},
				{Value: "x4plus", Label: "x4plus (photographs)"},
				{Value: "x2plus", Label: "x2plus (photographs, lighter)"},
			}},
			{Name: "scale", Label: "Scale", Type: ParamNumber, Default: "2.0", Min: 1.0, Max: 4.0, Step: 0.1},
			{Name: "tile", Label: "Tile size", Type: ParamNumber, Default: "400", Min: 0, Max: 1024, Step: 16,
				Help: "Splits large images to bound memory. 0 disables tiling."},
		},
	},
}
